[package]
name = "rapt"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.23.8"
num-complex = "0.3"

[lib]
path="src/lib.rs"
name="rapt"
